<h2><?php echo $this->translate('Content') ?></h2>

<?php echo $this->RtFilterForm($this->form) ?>

<table class="MWPTABLE">
     <tr>
         <th style="text-align:left"><?php echo $this->translate('Id');?><br><font size="1" color="green">
            <?php echo $this->translate('Lang.');?></font></th>
         <th style="text-align:left"><?php echo $this->translate('Name');?><br><font size="1" color="green">
             <?php echo $this->translate('Content type');?></font></th>
         <th style="text-align:left" width="90"><?php echo $this->translate('Date');?><br><font size="1" color="green">
             <?php echo $this->translate('Time');?></font></th>
         <th style="text-align:right" width="90"><a href="<?php echo $this->url('contentmanager/content/add', array(
             'lang'=> $this->Lang(), 
             'page'=> $this->Param('page')));?>"title="<?php echo $this->translate('Add') ?>"><img src="/img/mwp_icons_empty.png" class="mwp-nbtn mwp-nbtn-add"></a></th>
     </tr>
     <?php foreach ($this->paginator as $row) : // <-- change here! ?>
         <tr>
             <td><?php echo $row->GetContentId();?><br><font size="1" color="green">
                <?php echo $row->GetLang()->GetName();?></font></td>
             <td><?php echo $row->GetName();?><br><font size="1" color="green">
                <?php echo '('.$row->GetContentType()->GetContentTypeId().') '.$row->GetContentType()->GetName();?></font></td>
             <td><?php echo $row->GetDt()->format('Y-m-d');?><br><font size="1" color="green">
                <?php echo $row->GetDt()->format('H:i:s');?></font></td>
             <td align="right">
                 <a href="<?php echo $this->url('contentmanager/content/edit', array(
                     'lang'=> $this->Lang(),
                     'id' => $row->GetContentId()));?>" title="<?php echo $this->translate('Edit') ?>"><img src="/img/mwp_icons_empty.png" class="mwp-nbtn mwp-nbtn-upd"></a>
                 <a href="<?php echo $this->url('contentmanager/content/copy', array(
                     'lang'=> $this->Lang(),
                     'id' =>  $row->GetContentId()));?>" title="<?php echo $this->translate('Create copy') ?>"><img src="/img/mwp_icons_empty.png" class="mwp-nbtn mwp-nbtn-cpa"></a>
                 <a href="#" title="<?php echo $this->translate('Delete') ?>"
                    onClick=
                        "if(confirm('<?php echo $this->translate('Are you sure you want to delete?') ?>')) {
                        href='<?php echo $this->url('contentmanager/content/delete', array(
                            'lang'=> $this->Lang(),
                            'id' => $row->GetContentId()));?>';} else return false;"><img src="/img/mwp_icons_empty.png" class="mwp-nbtn mwp-nbtn-del"></a>
             </td>
         </tr>
     <?php endforeach; ?>
</table>
<?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    'pagination/search',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'contentmanager/content'
    )
);
?>