<h2><?php echo $this->translate('Catalog of content types') ?></h2>

<?php echo $this->RtFilterForm($this->form) ?>

<table class="MWPTABLE">
     <tr>
         <th style="text-align:left"><?php echo $this->translate('Id');?></th>
         <th style="text-align:left"><?php echo $this->translate('Name');?></th>
         <th style="text-align:left"><?php echo $this->translate('Display type');?></th>         
         <th style="text-align:left"><?php echo $this->translate('Display date');?></th>
         <th style="text-align:left"><?php echo $this->translate('Display user');?></th>
         <th style="text-align:left"><?php echo $this->translate('Link type');?></th>
         <th style="text-align:left"><?php echo $this->translate('New page');?></th>
         <th style="text-align:right" width="90">
             <a href="<?php echo $this->url('contentmanager/contenttype/add', array(
                 'lang'=> $this->Lang(), 
                 'page'=> $this->Param('page')));?>"title="<?php echo $this->translate('Add') ?>"><img src="/img/mwp_icons_empty.png" class="mwp-nbtn mwp-nbtn-add"></a></th>
     </tr>
     <?php foreach ($this->paginator as $row) : // <-- change here! ?>
         <tr>
             <td><?php echo $row->GetContentTypeId();?></td>
             <td><?php echo $row->GetName();?></td>
             <td><?php echo $this->rtDisplayType($row->GetDisplayType());?></td>
             <td><input type="checkbox" <?php echo $row->GetDisplayDt()?'checked':'' ?> DISABLED/></td>
             <td><input type="checkbox" <?php echo $row->GetDisplayUser()?'checked':'' ?> DISABLED/></td>
             <td><?php echo $this->rtLinkType($row->GetLinkType());?></td>
             <td><input type="checkbox" <?php echo $row->GetOpenNewPage()?'checked':'' ?> DISABLED/></td>             
             <td align="right">
                 <a href="<?php echo $this->url('contentmanager/contenttype/edit', array(
                     'lang'=> $this->Lang(),
                     'id' => $row->GetContentTypeId()));?>" title="<?php echo $this->translate('Edit') ?>"><img src="/img/mwp_icons_empty.png" class="mwp-nbtn mwp-nbtn-upd"></a>
                 <a href="<?php echo $this->url('contentmanager/contenttype/copy', array(
                     'lang'=> $this->Lang(),
                     'id' =>  $row->GetContentTypeId()));?>" title="<?php echo $this->translate('Create copy') ?>"><img src="/img/mwp_icons_empty.png" class="mwp-nbtn mwp-nbtn-cpa"></a>
                 <a href="#" title="<?php echo $this->translate('Delete') ?>" 
                    onClick=
                        "if(confirm('<?php echo $this->translate('All related records will be deleted! Are you sure you want to delete?') ?>')) {
                        href='<?php echo $this->url('contentmanager/contenttype/delete', array(
                            'lang'=> $this->Lang(), 
                            'id' => $row->GetContentTypeId()));?>';} else return false;"><img src="/img/mwp_icons_empty.png" class="mwp-nbtn mwp-nbtn-del"></a>             
             </td>
         </tr>
     <?php endforeach; ?>
</table>
<?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    'pagination/search',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'contentmanager/contenttype'
    )
);
?>